stages:
  - build
  - test
  - manifest
  - deploy

amd64 docker build:
  stage: yobasystems/alpine-docker:dind
  stage: build
  tags:
    - amd64
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_APPLICATION_TAG)
    - echo "$COMMIT_TIME" && echo "$CI_COMMIT_SHORT_SHA"
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-docker-amd64/ && docker build --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA} --build-arg BUILD_DATE=${COMMIT_TIME} -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:x86_64 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:x86_64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:amd64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:x86_64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:x86_64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:x86_64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:amd64 .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:x86_64
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:x86_64
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:x86_64
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:amd64

amd64 dind build:
  stage: yobasystems/alpine-docker:dind
  stage: build
  tags:
    - amd64
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_APPLICATION_TAG)
    - echo "$COMMIT_TIME" && echo "$CI_COMMIT_SHORT_SHA"
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-dind-amd64/ && docker build --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA} --build-arg BUILD_DATE=${COMMIT_TIME} -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:x86_64-dind -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-dind -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:x86_64-dind -t $DOCKER_REGISTRY_DOCKERHUB_REPO:x86_64-dind -t $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64-dind -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:amd64-dind .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:x86_64-dind
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-dind
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:x86_64-dind
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64-dind
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:x86_64-dind
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:amd64-dind

arm32v7 docker build:
  stage: yobasystems/alpine-docker:armhf-dind
  stage: build
  tags:
    - armhf
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_APPLICATION_TAG)
    - echo "$COMMIT_TIME" && echo "$CI_COMMIT_SHORT_SHA"
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-docker-armhf/ && docker build --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA} --build-arg BUILD_DATE=${COMMIT_TIME} -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf -t $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf

arm32v7 dind build:
  stage: yobasystems/alpine-docker:armhf-dind
  stage: build
  tags:
    - armhf
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_APPLICATION_TAG)
    - echo "$COMMIT_TIME" && echo "$CI_COMMIT_SHORT_SHA"
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-dind-armhf/ && docker build --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA} --build-arg BUILD_DATE=${COMMIT_TIME} -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-dind -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-dind -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7-dind -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf-dind -t $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf-dind -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf-dind .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-dind
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf-dind
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-dind
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf-dind
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7-dind
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf-dind

arm64v8 docker build:
  stage: yobasystems/alpine-docker:aarch64-dind
  stage: build
  tags:
    - aarch64
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_APPLICATION_TAG)
    - echo "$COMMIT_TIME" && echo "$CI_COMMIT_SHORT_SHA"
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-docker-aarch64/ && docker build --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA} --build-arg BUILD_DATE=${COMMIT_TIME} -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64 .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64

arm64v8 dind build:
  stage: yobasystems/alpine-docker:aarch64-dind
  stage: build
  tags:
    - aarch64
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_APPLICATION_TAG)
    - echo "$COMMIT_TIME" && echo "$CI_COMMIT_SHORT_SHA"
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-dind-aarch64/ && docker build --build-arg VCS_REF=${CI_COMMIT_SHORT_SHA} --build-arg BUILD_DATE=${COMMIT_TIME} -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-dind -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-dind -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8-dind -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64-dind -t $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64-dind -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64-dind .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-dind
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64-dind
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-dind
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64-dind
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8-dind
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64-dind

gitlab manifest creation:
  image: yobasystems/alpine-docker:amd64-dind
  stage: manifest
  tags:
    - amd64
  script:
    - mkdir /root/.docker
    - 'echo -e "{\n    \"experimental\": \"enabled\"\n}\n" >> ~/.docker/config.json'
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - docker pull $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64
    - docker pull $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7
    - docker pull $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8
    - docker manifest create $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64 $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7 $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8
    - docker manifest annotate $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64 --os linux --arch amd64
    - docker manifest annotate $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7 --os linux --arch arm
    - docker manifest annotate $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8 --os linux --arch arm64
    - docker manifest push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest

dockerhub manifest creation:
  image: yobasystems/alpine-docker:amd64-dind
  stage: manifest
  tags:
    - amd64
  script:
    - mkdir /root/.docker
    - 'echo -e "{\n    \"experimental\": \"enabled\"\n}\n" >> ~/.docker/config.json'
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64
    - docker pull $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7
    - docker pull $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8
    - docker manifest create $DOCKER_REGISTRY_DOCKERHUB_REPO:latest $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64 $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7 $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8
    - docker manifest annotate $DOCKER_REGISTRY_DOCKERHUB_REPO:latest $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64 --os linux --arch amd64
    - docker manifest annotate $DOCKER_REGISTRY_DOCKERHUB_REPO:latest $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7 --os linux --arch arm
    - docker manifest annotate $DOCKER_REGISTRY_DOCKERHUB_REPO:latest $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8 --os linux --arch arm64
    - docker manifest push $DOCKER_REGISTRY_DOCKERHUB_REPO:latest

gitlab manifest creation dind:
  image: yobasystems/alpine-docker:amd64-dind
  stage: manifest
  tags:
    - amd64
  script:
    - mkdir /root/.docker
    - 'echo -e "{\n    \"experimental\": \"enabled\"\n}\n" >> ~/.docker/config.json'
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - docker pull $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-dind
    - docker pull $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-dind
    - docker pull $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-dind
    - docker manifest create $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:dind $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-dind $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-dind $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-dind
    - docker manifest annotate $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:dind $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-dind --os linux --arch amd64
    - docker manifest annotate $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:dind $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-dind --os linux --arch arm
    - docker manifest annotate $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:dind $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-dind --os linux --arch arm64
    - docker manifest push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:dind

dockerhub manifest creation dind:
  image: yobasystems/alpine-docker:amd64-dind
  stage: manifest
  tags:
    - amd64
  script:
    - mkdir /root/.docker
    - 'echo -e "{\n    \"experimental\": \"enabled\"\n}\n" >> ~/.docker/config.json'
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64-dind
    - docker pull $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-dind
    - docker pull $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-dind
    - docker manifest create $DOCKER_REGISTRY_DOCKERHUB_REPO:dind $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64-dind $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-dind $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-dind
    - docker manifest annotate $DOCKER_REGISTRY_DOCKERHUB_REPO:dind $DOCKER_REGISTRY_DOCKERHUB_REPO:amd64-dind --os linux --arch amd64
    - docker manifest annotate $DOCKER_REGISTRY_DOCKERHUB_REPO:dind $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-dind --os linux --arch arm
    - docker manifest annotate $DOCKER_REGISTRY_DOCKERHUB_REPO:dind $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-dind --os linux --arch arm64
    - docker manifest push $DOCKER_REGISTRY_DOCKERHUB_REPO:dind

Github Mirror:
  stage: deploy
  tags:
    - deploy
  script:
    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@$GITHUB_REPO
    - git push https://$GITHUB_USERNAME:$GITHUB_PASSWORD@$GITHUB_REPO HEAD:master

Bitbucket Mirror:
  stage: deploy
  tags:
    - deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$BB_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'bitbucket.org' >> ~/.ssh/known_hosts
    - git push --mirror git@$BITBUCKET_REPO
    - git push git@$BITBUCKET_REPO HEAD:master
